/*
 * udcd_uvc config - companion app for the vita-udcd-uvc plugin.
 *
 * Edits ux0:/data/udcd_uvc.txt (the file the kernel plugin reads at boot) with
 * a GPU-accelerated vita2d UI (same stack as EQVita), so it runs at a smooth
 * 60 FPS and supports both buttons and the front touchscreen.
 */

#include <psp2/kernel/processmgr.h>
#include <psp2/sysmodule.h>
#include <psp2/ctrl.h>
#include <psp2/touch.h>
#include <psp2/io/fcntl.h>
#include <vita2d.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>

#define SCR_W		960
#define SCR_H		544
#define CONFIG_PATH	"ux0:/data/udcd_uvc.txt"

/* theme */
#define COL_BG		RGBA8(14, 17, 26, 255)
#define COL_HEADER	RGBA8(22, 28, 42, 255)
#define COL_ACCENT	RGBA8(0, 214, 180, 255)
#define COL_ROW		RGBA8(30, 35, 50, 255)
#define COL_ROW_SEL	RGBA8(40, 70, 70, 255)
#define COL_TEXT	RGBA8(236, 239, 245, 255)
#define COL_DIM		RGBA8(130, 138, 155, 255)
#define COL_BTN		RGBA8(46, 54, 74, 255)

static vita2d_pgf *font;

/* --------------------------------------------------------------------------
 * Config model
 */
/*
 * Resolution and frame rate are intentionally NOT here: the plugin advertises
 * every mode over UVC and the capture app (OBS, etc.) selects them. This app
 * only covers the Vita-side settings the host can't control.
 */
enum { O_SCREEN, O_TOGGLE, O_SUSPEND, O_DELAY, O_COUNT };

static int v_screen, v_toggle, v_suspend, v_delay;

static void config_defaults(void)
{
	v_screen = 1; v_toggle = 1; v_suspend = 1; v_delay = 15;
}

static int clampi(int v, int lo, int hi) { return v < lo ? lo : (v > hi ? hi : v); }

static unsigned int p_uint(const char *s)
{
	unsigned int v = 0;
	while (*s == ' ' || *s == '\t') s++;
	while (*s >= '0' && *s <= '9') v = v * 10 + (unsigned int)(*s++ - '0');
	return v;
}

static void config_set(const char *key, const char *val)
{
	if (!strcmp(key, "screen_off"))           v_screen  = p_uint(val) ? 1 : 0;
	else if (!strcmp(key, "prevent_suspend")) v_suspend = p_uint(val) ? 1 : 0;
	else if (!strcmp(key, "screen_toggle"))   v_toggle  = p_uint(val) ? 1 : 0;
	else if (!strcmp(key, "livearea_delay"))  v_delay   = clampi((int)p_uint(val), 0, 30);
	/* res / fps are ignored here - the capture app picks those. */
}

static void config_load(void)
{
	char buf[1024], key[32], val[32];
	int ki = 0, vi = 0, in_val = 0, comment = 0, n, i;
	SceUID fd;

	config_defaults();
	fd = sceIoOpen(CONFIG_PATH, SCE_O_RDONLY, 0);
	if (fd < 0) return;
	n = sceIoRead(fd, buf, sizeof(buf) - 1);
	sceIoClose(fd);
	if (n <= 0) return;
	buf[n] = '\0';

	for (i = 0; i <= n; i++) {
		char c = buf[i];
		if (c == '\n' || c == '\0') {
			key[ki] = '\0'; val[vi] = '\0';
			if (ki > 0 && in_val) config_set(key, val);
			ki = vi = in_val = comment = 0;
			continue;
		}
		if (comment || c == '\r') continue;
		if (c == '#' || c == ';') { comment = 1; continue; }
		if (!in_val) {
			if (c == '=') in_val = 1;
			else if (c != ' ' && c != '\t' && ki < 31) key[ki++] = c;
		} else if (c != ' ' && c != '\t' && vi < 31) {
			val[vi++] = c;
		}
	}
}

static int config_save(void)
{
	char buf[512];
	int len = snprintf(buf, sizeof(buf),
		"# udcd_uvc configuration (generated by the config app)\n"
		"# resolution & frame rate are chosen in your capture app (OBS, etc.)\n"
		"screen_off = %d\n"
		"screen_toggle = %d\n"
		"prevent_suspend = %d\n"
		"livearea_delay = %d\n",
		v_screen, v_toggle, v_suspend, v_delay);
	SceUID fd = sceIoOpen(CONFIG_PATH, SCE_O_WRONLY | SCE_O_CREAT | SCE_O_TRUNC, 0666);
	if (fd < 0) return fd;
	sceIoWrite(fd, buf, len);
	sceIoClose(fd);
	return 0;
}

static void config_adjust(int sel, int dir)
{
	switch (sel) {
	case O_SCREEN:  v_screen = !v_screen; break;
	case O_TOGGLE:  v_toggle = !v_toggle; break;
	case O_SUSPEND: v_suspend = !v_suspend; break;
	case O_DELAY:   v_delay = clampi(v_delay + dir, 0, 30); break;
	}
}

static const char *opt_label(int i)
{
	switch (i) {
	case O_SCREEN:  return "Screen off while capturing";
	case O_TOGGLE:  return "SELECT+UP screen toggle";
	case O_SUSPEND: return "Keep console awake";
	case O_DELAY:   return "Startup delay";
	}
	return "";
}

static void opt_value(int i, char *out, int n)
{
	switch (i) {
	case O_SCREEN:  snprintf(out, n, "%s", v_screen ? "On" : "Off"); break;
	case O_TOGGLE:  snprintf(out, n, "%s", v_toggle ? "On" : "Off"); break;
	case O_SUSPEND: snprintf(out, n, "%s", v_suspend ? "On" : "Off"); break;
	case O_DELAY:   snprintf(out, n, "%d s", v_delay); break;
	}
}

/* --------------------------------------------------------------------------
 * Layout / drawing helpers
 */
#define LIST_X	60
#define LIST_Y0	150
#define ROW_H	72
#define ROW_W	840
#define BTN_W	48
#define BTN_H	44

typedef struct { float x, y, w, h; } Rect;

static int row_y(int i) { return LIST_Y0 + i * ROW_H; }
static Rect minus_rect(int i) { Rect r = { LIST_X + ROW_W - 250, row_y(i) + (ROW_H - BTN_H) / 2, BTN_W, BTN_H }; return r; }
static Rect plus_rect(int i)  { Rect r = { LIST_X + ROW_W - BTN_W, row_y(i) + (ROW_H - BTN_H) / 2, BTN_W, BTN_H }; return r; }
static Rect row_rect(int i)   { Rect r = { LIST_X, row_y(i), ROW_W - 260, ROW_H - 8 }; return r; }
static Rect save_rect(void)   { Rect r = { LIST_X, 478, 200, 50 }; return r; }
static Rect exit_rect(void)   { Rect r = { LIST_X + ROW_W - 200, 478, 200, 50 }; return r; }

static int hit(Rect r, float px, float py)
{
	return px >= r.x && px < r.x + r.w && py >= r.y && py < r.y + r.h;
}

static void txt(int x, int y, float scale, unsigned int color, const char *s)
{
	vita2d_pgf_draw_text(font, x, y, color, scale, s);
}
static void txt_center(int cx, int y, float scale, unsigned int color, const char *s)
{
	int w = vita2d_pgf_text_width(font, scale, s);
	vita2d_pgf_draw_text(font, cx - w / 2, y, color, scale, s);
}
static void fillr(Rect r, unsigned int c) { vita2d_draw_rectangle(r.x, r.y, r.w, r.h, c); }

static void button(Rect r, const char *label, unsigned int bg, unsigned int fg)
{
	fillr(r, bg);
	txt_center((int)(r.x + r.w / 2), (int)(r.y + r.h / 2 + 8), 1.1f, fg, label);
}

int main(void)
{
	sceSysmoduleLoadModule(SCE_SYSMODULE_PGF);
	vita2d_init();
	vita2d_set_vblank_wait(1);
	vita2d_set_clear_color(COL_BG);
	font = vita2d_load_default_pgf();

	config_load();
	sceCtrlSetSamplingMode(SCE_CTRL_MODE_ANALOG);
	sceTouchSetSamplingState(SCE_TOUCH_PORT_FRONT, SCE_TOUCH_SAMPLING_STATE_START);

	int sel = 0;
	float hl_y = LIST_Y0, intro = 0.0f, flash = 0.0f, toast = 0.0f;
	unsigned int prev_btn = 0;
	int prev_touch = 0, hold = 0;

	for (;;) {
		/* ---- input ---- */
		SceCtrlData pad;
		sceCtrlPeekBufferPositive(0, &pad, 1);
		unsigned int now = pad.buttons, down = now & ~prev_btn;

		if (down & SCE_CTRL_UP)   sel = (sel + O_COUNT - 1) % O_COUNT;
		if (down & SCE_CTRL_DOWN) sel = (sel + 1) % O_COUNT;

		int dir = 0;
		if (down & SCE_CTRL_LEFT)  dir = -1;
		if (down & SCE_CTRL_RIGHT) dir = +1;
		if (now & (SCE_CTRL_LEFT | SCE_CTRL_RIGHT)) {
			if (++hold > 22 && (hold % 4) == 0)
				dir = (now & SCE_CTRL_LEFT) ? -1 : +1;
		} else {
			hold = 0;
		}
		if (dir) { config_adjust(sel, dir); flash = 1.0f; }

		if (down & SCE_CTRL_CROSS)  { config_save(); toast = 1.0f; }
		if (down & SCE_CTRL_START)  { config_save(); break; }
		if (down & SCE_CTRL_CIRCLE) break;
		prev_btn = now;

		/* ---- touch ---- */
		SceTouchData tp;
		sceTouchPeek(SCE_TOUCH_PORT_FRONT, &tp, 1);
		if (tp.reportNum > 0 && !prev_touch) {
			float px = tp.report[0].x / 2.0f;   /* panel 1920x1088 -> 960x544 */
			float py = tp.report[0].y / 2.0f;
			for (int i = 0; i < O_COUNT; i++) {
				if (hit(row_rect(i), px, py)) sel = i;
				if (hit(minus_rect(i), px, py)) { sel = i; config_adjust(i, -1); flash = 1.0f; }
				if (hit(plus_rect(i), px, py))  { sel = i; config_adjust(i, +1); flash = 1.0f; }
			}
			if (hit(save_rect(), px, py)) { config_save(); toast = 1.0f; }
			if (hit(exit_rect(), px, py)) break;
		}
		prev_touch = (tp.reportNum > 0);

		/* ---- animation ---- */
		hl_y += (row_y(sel) - hl_y) * 0.30f;
		intro += 0.06f; if (intro > 1.0f) intro = 1.0f;
		flash -= 0.07f; if (flash < 0.0f) flash = 0.0f;
		toast -= 0.012f; if (toast < 0.0f) toast = 0.0f;
		int slide = (int)((1.0f - intro) * (1.0f - intro) * 60.0f);

		/* ---- draw ---- */
		vita2d_start_drawing();
		vita2d_clear_screen();

		/* header */
		vita2d_draw_rectangle(0, 0, SCR_W, 96, COL_HEADER);
		vita2d_draw_rectangle(0, 96, SCR_W, 3, COL_ACCENT);
		txt(LIST_X, 50, 1.9f, COL_TEXT, "udcd-uvc");
		txt(LIST_X, 80, 1.0f, COL_ACCENT, "capture configuration");

		/* animated selection highlight */
		{
			Rect h = { LIST_X - 14, hl_y - 4, ROW_W + 28, ROW_H - 8 };
			unsigned int c = (flash > 0.0f)
				? RGBA8(40, 90 + (int)(flash * 60), 86 + (int)(flash * 50), 255)
				: COL_ROW_SEL;
			fillr(h, c);
			vita2d_draw_rectangle(h.x, h.y, 6, h.h, COL_ACCENT);
		}

		/* rows */
		for (int i = 0; i < O_COUNT; i++) {
			int y = row_y(i) + slide;
			int selrow = (i == sel);
			char val[40];
			opt_value(i, val, sizeof(val));

			txt(LIST_X + 8, y + 46, 1.1f, selrow ? COL_TEXT : COL_DIM, opt_label(i));

			Rect mn = minus_rect(i), pl = plus_rect(i);
			mn.y += slide; pl.y += slide;
			button(mn, "<", selrow ? COL_BTN : COL_ROW, selrow ? COL_ACCENT : COL_DIM);
			button(pl, ">", selrow ? COL_BTN : COL_ROW, selrow ? COL_ACCENT : COL_DIM);
			txt_center((int)((mn.x + mn.w + pl.x) / 2), y + 46, 1.2f,
				   selrow ? COL_ACCENT : COL_TEXT, val);
		}

		/* footer buttons */
		button(save_rect(), "SAVE", COL_ACCENT, COL_BG);
		button(exit_rect(), "EXIT", COL_BTN, COL_TEXT);
		txt_center(SCR_W / 2, 508, 0.9f, COL_DIM,
			   "D-Pad / touch to navigate   X save   O exit");

		/* saved toast */
		if (toast > 0.0f) {
			int a = (int)(toast > 0.85f ? 255 : toast / 0.85f * 255);
			vita2d_draw_rectangle(SCR_W / 2 - 230, 110, 460, 44,
				RGBA8(0, 214, 180, a * 90 / 255));
			txt_center(SCR_W / 2, 140, 1.0f, RGBA8(236, 239, 245, a),
				   "Saved - reboot to apply");
		}

		vita2d_end_drawing();
		vita2d_swap_buffers();
	}

	vita2d_fini();
	vita2d_free_pgf(font);
	sceKernelExitProcess(0);
	return 0;
}
